name: Put comment on PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  comment:
    name: comment - ${{ github.event.pull_request.head.ref }}
    if: github.event.pull_request && github.event.action != 'closed' && github.event.pull_request.merged == false && contains(github.event.pull_request.title, 'INFRA') == false
    runs-on: ubuntu-latest
    steps:
      - name: Post PR comment with Storybook URL
        if: github.event.action != 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Storybook is deployed at: https://${github.event.pull_request.head.ref}-storybook.babo.3o3.co.kr`
            });
